---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install Packages for django
  apt:
    name: "{{ item }}"
    state: "installed"
  with_items: "{{ __csdt_django_packages }}"

- name: Install pexpect
  pip:
    name: pexpect

- name: harp - install harp
  npm:
    name: harp
    global: yes
    state: present
